export interface IPersona {
  nombrePropio1?:string;
  nombrePropio2?:string;
  apellidoPaterno?:string;
  apellidoMaterno?:string;
  edad?:number;
  genero?:string;
  sexoReferido?:string;
  sexoAlNacer?:string;
  esPersonal?:boolean;
  esDerechoHabiente?:boolean;
  nss?:string;
  derechoHabiencia?:string;
  ocupacion?:string;
  curp?:string;
  fechaNacimiento?:string;
  fechaRegistro?:Date;
  nacionalidad?:string;
  religion?:string;
  talla?:number;
  folioPaciente?:string;
  meses?:string;
}
